title: Duino-Based Learning (DBL)
author: ETSEIB & MathWorks

description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
# social links
github_username:  DuinoBasedLearning
youtube_username: Eneko Lerma - DuinoBasedLearning
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
youtube_username: jekyll
# googleplus_username: +jekyll

theme: minima
